---
title: "Linear models for ECG data"
author: "Joonatan Palmu"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
editor_options: 
  chunk_output_type: console
---

# Init

```{r options, include = FALSE}
knitr::opts_chunk$set(include = TRUE, echo = TRUE, message = FALSE, results='asis', cache=FALSE, warning=FALSE, collapse = TRUE, error = TRUE)
```

# Devtools

```{r devtools}
devtools::load_all(quiet = TRUE)
```

## Function factories

```{r}
mysave <- mysavefactory()
```

## Plot settings

```{r}
{ ggthemes::theme_tufte(base_family = "sans", base_size = 12) +
    ggplot2::theme(panel.border = ggplot2::element_rect(colour = "black", fill = NA),
                   panel.background = ggplot2::element_rect(fill = NA, color = NA),
                   plot.background = ggplot2::element_rect(fill = NA, color = NA), 
                   axis.text = ggplot2::element_text(colour = "black", size = 10)) } %>%
  ggplot2::theme_set()
```

## Read pgs data

```{r}
df_pgs <- readr::read_tsv("df_pgs.tsv")
```

```{r}
df_plot <- df_pgs %>%
  dplyr::filter(term != "(Intercept)") %>%
  dplyr::mutate(estimate = ifelse(term == "ECG_EVENT_AGE", 10*estimate, estimate)) %>% 
  dplyr::mutate(conf.low = ifelse(term == "ECG_EVENT_AGE", 10*conf.low, conf.low)) %>% 
  dplyr::mutate(conf.high = ifelse(term == "ECG_EVENT_AGE", 10*conf.high, conf.high)) %>% 
  dplyr::mutate(term = dplyr::case_when(term == "SEX_IMPUTED1" ~ "Sex",
                                        term == "PRS_SCORE" ~ "Polygenic risk score",
                                        term == "N14_CHRONKIDNEYDIS1" ~ "Chronic kidney disease",
                                        term == "I9_HEARTFAIL1" ~ "Heart failure",
                                        term == "I9_CHD1" ~ "Coronary heart disease",
                                        term == "ECG_EVENT_AGE" ~ "Per 10 years of age",
                                        term == "E4_DIABETES1" ~ "Diabetes",
                                        TRUE ~ term)) %>%
  dplyr::mutate(star = glue::glue("{ifelse(p.value < 0.001, 'P<0.001', sprintf('P=%.3f', p.value))}")) %>%
  dplyr::mutate(label = glue::glue("{sprintf('%.1f', estimate)} ({sprintf('%.1f', conf.low)} to {sprintf('%.1f', conf.high)})"))
```


```{r}
panelA <-ggplot2::ggplot(df_plot, ggplot2::aes(x = forcats::fct_rev(term), y = estimate, ymin = conf.low, ymax = conf.high)) +
  ggplot2::coord_flip(clip = "off") +
  ggplot2::geom_pointrange() +    
  ggplot2::geom_hline(yintercept = 0, linetype = "dashed") +
  ggplot2::scale_y_continuous(expand = c(0.01, 0.01),
                              breaks = seq(-80, 80, 10),
                              limits = c(-30, 30)) +
  ggplot2::labs(x = NULL, y = NULL) 
```

```{r}
panelB <- ggplot2::ggplot(df_plot, ggplot2::aes(x = forcats::fct_rev(term))) +
  ggplot2::coord_flip(clip = "off") +
  ggplot2::geom_text(ggplot2::aes(label = label, y = "β (95% CI)"), hjust = 0.5) +
  ggplot2::labs(x = NULL, y = NULL) +
  ggplot2::theme(axis.text.y = ggplot2::element_blank(),
                 panel.grid.major = ggplot2::element_blank(),
                 panel.grid.minor = ggplot2::element_blank(),
                 panel.border = ggplot2::element_blank(),
                 panel.grid = ggplot2::element_blank(),
                 axis.ticks.y = ggplot2::element_blank()) 
```

```{r}
panelC <- ggplot2::ggplot(df_plot, ggplot2::aes(x = forcats::fct_rev(term))) +
  ggplot2::coord_flip(clip = "off") +
  ggplot2::geom_text(ggplot2::aes(label = star, y = "P"), hjust = 0.5) +
  ggplot2::labs(y = NULL, x = NULL) +
  ggplot2::theme(axis.text.y = ggplot2::element_blank(),
                 panel.grid.major = ggplot2::element_blank(),
                 panel.grid.minor = ggplot2::element_blank(),
                 panel.border = ggplot2::element_blank(),
                 panel.grid = ggplot2::element_blank(),
                 axis.ticks.y = ggplot2::element_blank()) 
```

```{r}
patchwork::wrap_plots(panelA, panelB, panelC, widths = c(2, 2, 1)) %>%
  mysave("forest_pgs", width = 7, height = 3)
```



## Read med models data

```{r}
df_meds <- readr::read_tsv("df_meds.tsv")
```

```{r}
df_plot <- df_meds %>%
  dplyr::filter(term == "med1", qval < 0.05) %>%
    dplyr::mutate(ATC = stringr::str_extract(model, "(?<=\\().*?(?=\\))")) %>%
  dplyr::mutate(med = stringr::str_extract(model, ".*(?= \\()")) %>%
    dplyr::mutate(med = stringr::str_c(med, collapse = "\n"), .by = "ATC") %>%
    dplyr::select(-model, -term) %>%
    dplyr::mutate(med = dplyr::case_when(ATC == "G03FB05" ~ "Norethisterone and estrogen",
                                         ATC == "L02AE02" ~ "Leuprorelin",
                                         TRUE ~ med)) %>%
    unique() %>%
    dplyr::mutate(star = glue::glue("{ifelse(qval < 0.001, 'P<0.001', sprintf('P=%.3f', qval))}")) %>%
    dplyr::mutate(label = glue::glue("{sprintf('%.1f', estimate)} ({sprintf('%.1f', conf.low)} to {sprintf('%.1f', conf.high)})"))

```


```{r}
panelA <-ggplot2::ggplot(df_plot, ggplot2::aes(x = forcats::fct_rev(med), y = estimate, ymin = conf.low, ymax = conf.high)) +
  ggplot2::coord_flip(clip = "off") +
  ggplot2::geom_pointrange() +    
  ggplot2::geom_hline(yintercept = 0, linetype = "dashed") +
  ggplot2::scale_y_continuous(expand = c(0.01, 0.01),
                              breaks = seq(-80, 80, 20),
                              limits = c(-80, 80)) +
  ggplot2::labs(x = NULL, y = NULL) 
```

```{r}
panelB <- ggplot2::ggplot(df_plot, ggplot2::aes(x = forcats::fct_rev(med))) +
  ggplot2::coord_flip(clip = "off") +
  ggplot2::geom_text(ggplot2::aes(label = label, y = "β (95% CI)"), hjust = 0.5) +
  ggplot2::labs(x = NULL, y = NULL) +
  ggplot2::theme(axis.text.y = ggplot2::element_blank(),
                 panel.grid.major = ggplot2::element_blank(),
                 panel.grid.minor = ggplot2::element_blank(),
                 panel.border = ggplot2::element_blank(),
                 panel.grid = ggplot2::element_blank(),
                 axis.ticks.y = ggplot2::element_blank()) 
```

```{r}
panelC <- ggplot2::ggplot(df_plot, ggplot2::aes(x = forcats::fct_rev(med))) +
  ggplot2::coord_flip(clip = "off") +
  ggplot2::geom_text(ggplot2::aes(label = star, y = "P"), hjust = 0.5) +
  ggplot2::labs(y = NULL, x = NULL) +
  ggplot2::theme(axis.text.y = ggplot2::element_blank(),
                 panel.grid.major = ggplot2::element_blank(),
                 panel.grid.minor = ggplot2::element_blank(),
                 panel.border = ggplot2::element_blank(),
                 panel.grid = ggplot2::element_blank(),
                 axis.ticks.y = ggplot2::element_blank()) 
```

```{r}
patchwork::wrap_plots(panelA, panelB, panelC, widths = c(2, 2, 1)) %>%
  mysave("forest_med", width = 7, height = 4)
```

