---
title: "Linear models for ECG data"
author: "Joonatan Palmu"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
editor_options: 
  chunk_output_type: console
---

# Init

```{r options, include = FALSE}
knitr::opts_chunk$set(include = TRUE, echo = TRUE, message = FALSE, results='asis', cache=FALSE, warning=FALSE, collapse = TRUE, error = TRUE)
```

# Devtools

```{r devtools}
devtools::load_all(quiet = TRUE)
```

## Function factories

```{r}
mysave <- mysavefactory()
```

## Plot settings

```{r}
{ ggthemes::theme_tufte(base_family = "sans", base_size = 12) +
    ggplot2::theme(panel.border = ggplot2::element_rect(colour = "black", fill = NA),
                   panel.background = ggplot2::element_rect(fill = NA, color = NA),
                   plot.background = ggplot2::element_rect(fill = NA, color = NA), 
                   axis.text = ggplot2::element_text(colour = "black", size = 10)) } %>%
  ggplot2::theme_set()
```

# Results

## Characteristics

```{r}
df_binomial %>% table1::table1(~., data = .)
```

## PRS score

```{r}
df_lm <- stats::lm(QTCorrected ~ PRS_SCORE + ECG_EVENT_AGE + SEX_IMPUTED + N14_CHRONKIDNEYDIS + I9_CHD +E4_DIABETES + I9_HEARTFAIL,
          data = df_binomial) %>%
  broom::tidy(conf.int = TRUE)
```

```{r}
df_lm %>% DT::datatable()
```

```{r}
{ df_lm %>%
  dplyr::filter(term != "(Intercept)") %>%
  dplyr::mutate(term = dplyr::case_when(term == "SEX_IMPUTED1" ~ "Sex",
                                        term == "PRS_SCORE" ~ "Polygenic risk score",
                                        term == "N14_CHRONKIDNEYDIS1" ~ "Chronic kidney disease",
                                        term == "I9_HEARTFAIL1" ~ "Heart failure",
                                        term == "I9_CHD1" ~ "Coronary heart disease",
                                        term == "ECG_EVENT_AGE" ~ "Age",
                                        term == "E4_DIABETES1" ~ "Diabetes",
                                        TRUE ~ term)) %>%
  dplyr::mutate(star = glue::glue("{ifelse(p.value < 0.001, 'P<0.001', sprintf('P=%.3f', p.value))}")) %>%
  ggplot2::ggplot(ggplot2::aes(x = forcats::fct_rev(term), y = estimate, ymin = conf.low, ymax = conf.high)) +
  ggplot2::geom_pointrange() +
  ggplot2::geom_text(ggplot2::aes(label = star, y = 28), hjust = 0) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dashed") +
  ggplot2::coord_flip() +
  ggplot2::scale_y_continuous(name = NULL,
                              expand = c(0.01, 0.01),
                              breaks = seq(-10, 25, 10),
                              limits = c(-10, 35)) +
  ggplot2::labs(x = NULL, y = "Coefficient Estimate (95% CI)") } %>%
  mysave("forest_prs", width = 6, height = 4)
```

## Distinct medications

```{r}
meds <- df_binomial %>% colnames %>% stringr::str_subset('\\)$')
```

```{r}
lm_partial <- purrr::partial(stats::lm,
                             formula = QTCorrected ~ med + ECG_EVENT_AGE + SEX_IMPUTED + N14_CHRONKIDNEYDIS + I9_CHD + 
                               E4_DIABETES + I9_HEARTFAIL + PRS_SCORE) %>%
  purrr::possibly()
```


```{r}
df_meds <- meds %>%
  setNames(., .) %>%
  purrr::map(~lm_partial(data = df_binomial %>% dplyr::rename(med = !!.x))) %>%
  purrr::map_df(~broom::tidy(.x, conf.int = TRUE), .id = "model") %>%
  dplyr::mutate(qval = p.adjust(p.value, method = "BH"), .by = term)
```


```{r}
readr::write_tsv(df_meds, "df_meds.tsv")
```


```{r}
{ df_meds %>% 
  dplyr::filter(term == "med1", qval < 0.05) %>%
  dplyr::mutate(ATC = stringr::str_extract(model, "(?<=\\().*?(?=\\))")) %>%
  dplyr::mutate(med = stringr::str_extract(model, ".*(?= \\()")) %>%
  dplyr::mutate(med = stringr::str_c(med, collapse = "\n"), .by = "ATC") %>%
  dplyr::select(-model, -term) %>%
  dplyr::mutate(med = dplyr::case_when(ATC == "G03FB05" ~ "Norethisterone and estrogen",
                                       ATC == "L02AE02" ~ "Leuprorelin",
                                       TRUE ~ med)) %>%
  unique() %>%
  dplyr::mutate(star = glue::glue("{ifelse(qval < 0.001, 'P<0.001', sprintf('P=%.3f', qval))}")) %>%
  ggplot2::ggplot(ggplot2::aes(x = forcats::fct_rev(med), y = estimate, ymin = conf.low, ymax = conf.high)) +
  ggplot2::geom_pointrange() +
  ggplot2::geom_text(ggplot2::aes(label = star, y = 70), hjust = 0) + 
  ggplot2::geom_hline(yintercept = 0, linetype = "dashed") +
  ggplot2::coord_flip() +
  ggplot2::scale_y_continuous(name = "Coefficient Estimate (95% CI)",
                              expand = c(0.01, 0.01),
                              breaks = seq(-80, 60, 20),
                              limits = c(-80, 100)) +
  ggplot2::labs(x = NULL) } %>%
  mysave("forest_med", width = 6, height = 4)

```

