---
title: "XGBoost result plotter"
author: "Joonatan Palmu"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
editor_options: 
  chunk_output_type: console
---

# Init

```{r options, include = FALSE}
knitr::opts_chunk$set(include = TRUE, echo = TRUE, message = FALSE, results='asis', cache=FALSE, warning=FALSE, collapse = TRUE, error = TRUE)
```

# Devtools

```{r devtools}
devtools::load_all(quiet = TRUE)
```

## Function factories

```{r}
mysave <- mysavefactory()
```

## Plot settings

```{r}
{ ggthemes::theme_tufte(base_family = "sans", base_size = 12) +
    ggplot2::theme(panel.border = ggplot2::element_rect(colour = "black", fill = NA),
                   panel.background = ggplot2::element_rect(fill = NA, color = NA),
                   plot.background = ggplot2::element_rect(fill = NA, color = NA), 
                   axis.text = ggplot2::element_text(colour = "black", size = 10)) } %>%
  ggplot2::theme_set()
```

# Load data

```{r}
df_xgboost <- readr::read_tsv("inst/extdata/xgboost.tsv") %>%
  dplyr::filter(Feature != "Norethisterone acetate (G03FB05)") %>%
  dplyr::mutate(Feature = dplyr::case_when(Feature == "Estradiol hemihydrate (G03FB05)" ~
                                             "Norethisterone and estrogen (G03FB05)",
                                           TRUE ~ Feature))
```

```{r}
facet_labels <- c("Gain_full" = "Full model gain", "Gain_basic" = "Basic model gain", "Shapley_full" = "Shapley values")
custom_colors <- c("TRUE" = "#000000", "FALSE" = "gray40")
```

```{r}
df_lm_meds <- readr::read_tsv("inst/extdata/df_meds.tsv") %>%
  dplyr::filter(term == "med1") %>%
  dplyr::mutate(model = dplyr::case_when(model == "Estradiol hemihydrate (G03FB05)" ~
                                             "Norethisterone and estrogen (G03FB05)",
                                           TRUE ~ model)) %>% 
  dplyr::select(model, estimate, qval)
```

```{r}
df <- df_xgboost %>%
  dplyr::select(Feature, Gain_basic, Gain_full, Shapley_full, Marginal) %>%
  dplyr::mutate(order = Gain_full) %>%
  tidyr::gather(key, value, Gain_basic, Gain_full, Shapley_full) %>%
  dplyr::left_join(df_lm_meds, by = dplyr::join_by(Feature == model)) %>%
  dplyr::mutate(key = factor(key, levels = c("Gain_basic", "Gain_full", "Shapley_full")))  %>%
  dplyr::mutate(color = stringr::str_detect(Feature, '\\(')) %>% 
  dplyr::mutate(Feature = gsub("\\(.*?\\)", "", Feature)) %>% 
  dplyr::mutate(Feature = dplyr::case_when(Feature == "PRS_SCORE" ~ "Polygenic risk score",
                                           Feature == "ECG_EVENT_AGE" ~ "Age",
                                           Feature == "I9_HEARTFAIL" ~ "Heart failure",
                                           Feature == "SEX_IMPUTED" ~ "Sex",
                                           Feature == "E4_DIABETES" ~ "Diabetes",
                                           TRUE ~ Feature)) %>%
  dplyr::mutate(star = ifelse(qval < 0.05 & key == "Gain_full", TRUE, FALSE))
```

```{r}
p1 <- ggplot2::ggplot(df, ggplot2::aes(x = forcats::fct_reorder(Feature, order),
                                       y = value,
                                       fill = color)) +
  ggplot2::facet_wrap(~key, labeller = ggplot2::labeller(key = facet_labels)) +
  ggplot2::geom_bar(stat = "identity", position = "dodge") +
  ggplot2::scale_x_discrete(name = NULL) +
  ggplot2::scale_y_continuous(name = "Feature importance in\ngrandient boosting ML model",
                              expand = c(0, 0),
                              breaks = seq(0, 1, 0.1)) +
  ggplot2::scale_fill_manual(guide = "none",
                             values = custom_colors) +
  ggplot2::coord_flip() 
```

```{r}
p2 <- df %>%
  dplyr::filter(key == "Gain_full") %>%
  dplyr::mutate(estimate_label = ifelse(is.na(estimate), "", sprintf("%+.0f", estimate))) %>%
  dplyr::mutate(Marginal_label = ifelse(is.na(Marginal), "", sprintf("%+.0f", Marginal))) %>% 
  ggplot2::ggplot(ggplot2::aes(x = forcats::fct_reorder(Feature, order))) +
  ggplot2::geom_tile(ggplot2::aes(y = factor("β"), fill = estimate)) +
  ggplot2::geom_text(ggplot2::aes(y = factor("β"), label = estimate_label), hjust = 0.5, size = 3) +
  ggplot2::geom_tile(ggplot2::aes(y = factor("ML"), fill = Marginal)) +
  ggplot2::geom_text(ggplot2::aes(y = factor("ML"), label = Marginal_label), hjust = 0.5, size = 3) +
  ggplot2::scale_fill_gradient2(name = NULL,
                                low = "blue",
                                high = "red",
                                mid = "white",
                                na.value = "transparent",
                                midpoint = 0,
                                oob = scales::squish,
                                limits = c(-10, 10))+
  ggplot2::scale_shape_manual(values = c(127, 8), guide = "none") +
  ggplot2::labs(x = NULL, y = "Effect\nestimates") +
  ggplot2::guides(fill = ggplot2::guide_colorbar(barwidth = 0.5, barheight = 8)) +
  ggplot2::coord_flip() +
  ggplot2::theme(axis.text.y = ggplot2::element_blank())
```

```{r}
library(patchwork)
{p1 + p2 + plot_layout(ncol = 2, widths = c(20, 4)) } %>% 
  mysave("bars_xgboost", width = 7, height = 4) 
```

